# Generated by Django 4.2.7 on 2023-11-10 02:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tarefas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tarefa",
            options={"ordering": ["-data_de_execucao"]},
        ),
    ]
