# Generated by Django 4.2.7 on 2023-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alunos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="data de execução"
                    ),
                ),
                ("nome", models.CharField(max_length=200, verbose_name="nome")),
                (
                    "datanascimento",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "cidade",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "logradouro",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "numero",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "bairro",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "cep",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "uf",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "telefone",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "email",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
                (
                    "cpf",
                    models.TextField(blank=True, null=True, verbose_name="descrição"),
                ),
            ],
            options={
                "ordering": ["-codigo"],
            },
        ),
    ]
