# Generated by Django 4.2.7 on 2023-11-13 23:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="bairro",
            field=models.CharField(max_length=200, verbose_name="Bairro"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="cep",
            field=models.CharField(max_length=20, verbose_name="CEP"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="cidade",
            field=models.CharField(max_length=200, null=True, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="codigo",
            field=models.CharField(max_length=20, null=True, verbose_name="codigo"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="cpf",
            field=models.CharField(max_length=200, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="datanascimento",
            field=models.CharField(max_length=200, verbose_name="Data Nascimento"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="email",
            field=models.CharField(max_length=200, verbose_name="e-mail"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="logradouro",
            field=models.CharField(max_length=200, verbose_name="Logradouro"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="nome",
            field=models.CharField(max_length=200, null=True, verbose_name="Nome"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="numero",
            field=models.CharField(max_length=20, verbose_name="Numero"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="telefone",
            field=models.CharField(max_length=200, verbose_name="Telefone"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="uf",
            field=models.CharField(max_length=20, null=True, verbose_name="UF"),
        ),
    ]
