# Generated by Django 4.2.7 on 2023-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0003_alter_alunos_bairro_alter_alunos_cep_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="cidade",
            field=models.CharField(
                blank=True, default=9999, max_length=200, verbose_name="Cidade"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="alunos",
            name="uf",
            field=models.CharField(
                blank=True, default=9888, max_length=20, verbose_name="UF"
            ),
            preserve_default=False,
        ),
    ]
