# Generated by Django 4.2.7 on 2023-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alunos", "0004_alter_alunos_cidade_alter_alunos_uf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alunos",
            name="cidade",
            field=models.CharField(max_length=200, verbose_name="Cidade"),
        ),
        migrations.AlterField(
            model_name="alunos",
            name="uf",
            field=models.CharField(max_length=20, verbose_name="UF"),
        ),
    ]
