# Generated by Django 4.2.7 on 2023-11-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotecas_python", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliotecas",
            name="ano",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="ano de Criação"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecas",
            name="criador",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome do criardor"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecas",
            name="descricao",
            field=models.TextField(blank=True, null=True, verbose_name="descrição"),
        ),
        migrations.AlterField(
            model_name="bibliotecas",
            name="link",
            field=models.URLField(
                blank=True, null=True, verbose_name="link da Biblioteca"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecas",
            name="mantenedor",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="nome do mantenedor"
            ),
        ),
        migrations.AlterField(
            model_name="bibliotecas",
            name="openSource",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Open-Source"
            ),
        ),
    ]
