# Generated by Django 4.2.7 on 2023-11-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotecas_python", "0003_alter_bibliotecas_ano"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bibliotecas",
            name="ano",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="ano de Criação"
            ),
        ),
    ]
