# Generated by Django 4.2.7 on 2023-11-25 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("bibliotecas_python", "0004_alter_bibliotecas_ano"),
    ]

    operations = [
        migrations.AddField(
            model_name="bibliotecas",
            name="data_de_criacao",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="data de criação",
            ),
            preserve_default=False,
        ),
    ]
